// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirm": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Confirm registration student",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register"
                ],
                "summary": "Confirm registration student",
                "operationId": "Confirm registration student",
                "parameters": [
                    {
                        "description": "Confirm registration student",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registration.ConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration confirmed successfully."
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPBadRequestErrors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/confirm-period": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get confirmation period\nAPI for GET confirmation period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get confirmation period",
                "operationId": "Get confirmation period",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.RegistrationPeriodResponse"
                        }
                    }
                }
            }
        },
        "/confirm/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetches a single record using its unique ID from the confirmation collection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register"
                ],
                "summary": "Retrieves a record by ID from the confirmation collection",
                "operationId": "get-record-by-confirmation-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetRegistrationStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Record ID not found or invalid",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/courses": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get courses from studentID studentYear and studentSemester\nAPI for GET courses from studentID studentYear and studentSemester",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get courses from studentID studentYear and studentSemester",
                "operationId": "Get courses from studentID studentYear and studentSemester",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetCoursesResponse"
                        }
                    }
                }
            }
        },
        "/courses/{courseId}/sections": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get sections by course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get sections by course",
                "operationId": "Get sections by course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "section , firstName of Instructor",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "isReserveSeat, isInProgramStructure",
                        "description": "Filter",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetCourseSection"
                        }
                    }
                }
            }
        },
        "/courses/{courseId}/sections/{section}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get section detail by course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get section detail by course",
                "operationId": "Get section detail by course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Section",
                        "name": "section",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/registration.CourseSectionDetail"
                            }
                        }
                    }
                }
            }
        },
        "/debt": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get debt for the student in current semester\nAPI for getting debt for registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get debt",
                "operationId": "Get debt on the current semester",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.DebtResponse"
                        }
                    }
                }
            }
        },
        "/enrollment/history": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get enrollment history for the student in current semester",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get enrollment history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetEnrollmentHistoryResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get event registration\nAPI for GET event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get event registration",
                "operationId": "Get event registration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/registration.EventResponse"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Health checking for the service",
                "produces": [
                    "application/json"
                ],
                "summary": "Health Check",
                "operationId": "HealthCheckHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.Response"
                        }
                    }
                }
            }
        },
        "/history": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "View information that students have previously registered.\nAPI for GET courses for view information that students have previously registered",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get registration history",
                "operationId": "Get registration history data from student ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/registration.GetRegistrationHistoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/news/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get news by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Get news by ID",
                "operationId": "Get news by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "News ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.NewsResponse"
                        }
                    }
                }
            }
        },
        "/pre-registration": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "View information that students have pre registered.\nAPI for GET courses for view information that students have pre registered",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get pre registration history",
                "operationId": "Get pre registration history data from student ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/registration.GetPreRegistrationHistoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/submit": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Submit registration student",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register"
                ],
                "summary": "Submit registration student",
                "operationId": "Submit registration student",
                "parameters": [
                    {
                        "description": "Submit registration student",
                        "name": "RequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/registration.ConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration submitted successfully."
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPBadRequestErrors"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/submit/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetches a single record using its unique ID from the submission collection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register"
                ],
                "summary": "Retrieves a record by ID from the submission collection",
                "operationId": "get-record-by-submission-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetRegistrationStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Record ID not found or invalid",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/suggestion": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get suggested courses for a given academic year and semester",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subject"
                ],
                "summary": "Get suggested courses for a given academic year and semester",
                "operationId": "GetSuggestionCourses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.GetCoursesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/tokens": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "get token from registration service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "GetTokenHandler",
                "operationId": "GetTokenHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.HTTPError"
                        }
                    }
                }
            }
        },
        "/tracking-status": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get registration status.\nAPI for GET registration status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Register"
                ],
                "summary": "Get registration status",
                "operationId": "Get registration status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/registration.Tracking"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Version for the service",
                "produces": [
                    "application/json"
                ],
                "summary": "Version",
                "operationId": "VersionHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/version.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "client.InstructorHistory": {
            "type": "object",
            "properties": {
                "extendPrefix": {
                    "type": "string"
                },
                "extendPrefixEng": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "firstNameEng": {
                    "type": "string"
                },
                "instructorId": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "lastNameEng": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "prefixEng": {
                    "type": "string"
                }
            }
        },
        "client.SchedulesHistory": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "weekDay": {
                    "type": "integer"
                },
                "weekDayName": {
                    "type": "string"
                }
            }
        },
        "health.Response": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "httputil.ErrorCode": {
            "type": "string",
            "enum": [
                "0001",
                "0002",
                "0003",
                "0004",
                "0005",
                "0006",
                "9999"
            ],
            "x-enum-varnames": [
                "BadRequest",
                "NotFound",
                "CreateUserError",
                "StatusForbidden",
                "StatusUnauthorized",
                "InternalServerError",
                "InvalidStatus"
            ]
        },
        "httputil.HTTPBadRequestError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httputil.HTTPBadRequestErrors": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/httputil.ErrorCode"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httputil.HTTPBadRequestError"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httputil.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/httputil.ErrorCode"
                },
                "message": {
                    "type": "string"
                },
                "messageEn": {
                    "type": "string"
                }
            }
        },
        "registration.ConfirmCourseRequest": {
            "type": "object",
            "required": [
                "action",
                "classid",
                "coursecode",
                "courseid",
                "creditattempt",
                "grademode",
                "section"
            ],
            "properties": {
                "action": {
                    "type": "integer"
                },
                "classid": {
                    "type": "integer"
                },
                "coursecode": {
                    "type": "string"
                },
                "courseid": {
                    "type": "integer"
                },
                "creditattempt": {
                    "type": "number"
                },
                "grademode": {
                    "type": "string",
                    "enum": [
                        "GD",
                        "SW"
                    ]
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "registration.ConfirmCourseResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "integer"
                },
                "classid": {
                    "type": "integer"
                },
                "creditattempt": {
                    "type": "number"
                },
                "errorid": {
                    "type": "integer"
                },
                "errorstring": {
                    "type": "string"
                },
                "grademode": {
                    "type": "string"
                }
            }
        },
        "registration.ConfirmRequest": {
            "type": "object",
            "required": [
                "course",
                "ip"
            ],
            "properties": {
                "course": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.ConfirmCourseRequest"
                    }
                },
                "ip": {
                    "type": "string"
                }
            }
        },
        "registration.ConfirmResponse": {
            "type": "object",
            "properties": {
                "course": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.ConfirmCourseResponse"
                    }
                },
                "errorid": {
                    "type": "integer"
                },
                "errorstring": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "studentId": {
                    "type": "string"
                }
            }
        },
        "registration.CourseDetail": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string"
                },
                "courseCode": {
                    "type": "string"
                },
                "courseId": {
                    "type": "integer"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "courseTypeName": {
                    "type": "string"
                },
                "courseTypeNameEng": {
                    "type": "string"
                },
                "courseUnit": {
                    "type": "string"
                },
                "credittotal": {
                    "type": "integer"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "facultyNameEng": {
                    "type": "string"
                },
                "grademode": {
                    "type": "string"
                },
                "levelId": {
                    "type": "integer"
                },
                "levelName": {
                    "type": "string"
                },
                "levelNameEng": {
                    "type": "string"
                }
            }
        },
        "registration.CourseSectionDetail": {
            "type": "object",
            "properties": {
                "courseCode": {
                    "type": "string"
                },
                "courseDescription": {
                    "type": "string"
                },
                "courseId": {
                    "type": "integer"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "finalSchedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.CourseSectionDetailSchedule"
                    }
                },
                "midTermSchedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.CourseSectionDetailSchedule"
                    }
                },
                "programs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.Program"
                    }
                },
                "reserveFor": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.ReserveInfo"
                    }
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "registration.CourseSectionDetailSchedule": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                }
            }
        },
        "registration.CourseTracking": {
            "type": "object",
            "properties": {
                "course": {
                    "$ref": "#/definitions/registration.CourseTrackingDetail"
                },
                "errorString": {
                    "type": "string"
                },
                "errorid": {
                    "type": "integer"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.SectionTracking"
                    }
                }
            }
        },
        "registration.CourseTrackingDetail": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "integer"
                },
                "condition": {
                    "type": "string"
                },
                "courseCode": {
                    "type": "string"
                },
                "courseId": {
                    "type": "integer"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "courseTypeName": {
                    "type": "string"
                },
                "courseTypeNameEng": {
                    "type": "string"
                },
                "courseUnit": {
                    "type": "string"
                },
                "creditattempt": {
                    "type": "number"
                },
                "credittotal": {
                    "type": "integer"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "facultyNameEng": {
                    "type": "string"
                },
                "grademode": {
                    "type": "string"
                },
                "levelId": {
                    "type": "integer"
                },
                "levelName": {
                    "type": "string"
                },
                "levelNameEng": {
                    "type": "string"
                }
            }
        },
        "registration.CoursesResponse": {
            "type": "object",
            "properties": {
                "courseCode": {
                    "type": "string"
                },
                "courseId": {
                    "type": "integer"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "courseTypeName": {
                    "type": "string"
                },
                "courseTypeNameEng": {
                    "type": "string"
                },
                "courseUnit": {
                    "type": "string"
                },
                "creditTotal": {
                    "type": "integer"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "facultyNameEng": {
                    "type": "string"
                },
                "gradeMode": {
                    "type": "string"
                },
                "isInProgramStructure": {
                    "type": "boolean"
                },
                "isReserveSeat": {
                    "type": "boolean"
                },
                "levelId": {
                    "type": "integer"
                },
                "levelName": {
                    "type": "string"
                },
                "levelNameEng": {
                    "type": "string"
                }
            }
        },
        "registration.Debt": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "balance": {
                    "type": "number"
                },
                "courseCode": {
                    "type": "string"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "feeId": {
                    "type": "integer"
                },
                "feeName": {
                    "type": "string"
                },
                "feeNameEng": {
                    "type": "string"
                },
                "voucherName": {
                    "type": "string"
                }
            }
        },
        "registration.DebtResponse": {
            "type": "object",
            "properties": {
                "acadYear": {
                    "type": "string"
                },
                "debt": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.Debt"
                    }
                },
                "paid": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.Debt"
                    }
                },
                "process": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.Debt"
                    }
                },
                "semester": {
                    "type": "string"
                }
            }
        },
        "registration.EnrollmentHistory": {
            "type": "object",
            "properties": {
                "classId": {
                    "type": "integer"
                },
                "courseCode": {
                    "type": "string"
                },
                "courseId": {
                    "type": "integer"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "courseUnit": {
                    "type": "string"
                },
                "creditattempt": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "facultyNameEng": {
                    "type": "string"
                },
                "grademode": {
                    "type": "string"
                },
                "instructors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.Instructors"
                    }
                },
                "isInProgramStructure": {
                    "type": "boolean"
                },
                "isReserveSeat": {
                    "type": "boolean"
                },
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.SectionSchedules"
                    }
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "registration.EventResponse": {
            "type": "object",
            "properties": {
                "acadYear": {
                    "type": "integer"
                },
                "endDate": {
                    "type": "string"
                },
                "scheduleCode": {
                    "type": "integer"
                },
                "semester": {
                    "type": "integer"
                },
                "startDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "titleEng": {
                    "type": "string"
                }
            }
        },
        "registration.GetCourseSection": {
            "type": "object",
            "properties": {
                "acadYear": {
                    "type": "integer"
                },
                "course": {
                    "$ref": "#/definitions/registration.CourseDetail"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.SectionInfo"
                    }
                },
                "semester": {
                    "type": "integer"
                }
            }
        },
        "registration.GetCoursesResponse": {
            "type": "object",
            "properties": {
                "acadYear": {
                    "type": "integer"
                },
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.CoursesResponse"
                    }
                },
                "semester": {
                    "type": "integer"
                }
            }
        },
        "registration.GetEnrollmentHistoryResponse": {
            "type": "object",
            "properties": {
                "acadYear": {
                    "type": "string"
                },
                "enrollmentHistory": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.EnrollmentHistory"
                    }
                },
                "semester": {
                    "type": "string"
                }
            }
        },
        "registration.GetPreRegistrationHistoryResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "integer"
                },
                "classId": {
                    "type": "integer"
                },
                "condition": {
                    "type": "string"
                },
                "courseCode": {
                    "type": "string"
                },
                "courseId": {
                    "type": "integer"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "courseTypeName": {
                    "type": "string"
                },
                "courseTypeNameEng": {
                    "type": "string"
                },
                "courseUnit": {
                    "type": "string"
                },
                "creditattempt": {
                    "type": "integer"
                },
                "credittotal": {
                    "type": "integer"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "facultyNameEng": {
                    "type": "string"
                },
                "grademode": {
                    "type": "string"
                },
                "instructors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.InstructorHistory"
                    }
                },
                "isInProgramStructure": {
                    "type": "boolean"
                },
                "isReserveSeat": {
                    "type": "boolean"
                },
                "levelId": {
                    "type": "integer"
                },
                "levelName": {
                    "type": "string"
                },
                "levelNameEng": {
                    "type": "string"
                },
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.SchedulesHistory"
                    }
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "registration.GetRegistrationHistoryCourseResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "integer"
                },
                "courseCode": {
                    "type": "string"
                },
                "courseId": {
                    "type": "integer"
                },
                "courseName": {
                    "type": "string"
                },
                "courseNameEng": {
                    "type": "string"
                },
                "courseUnit": {
                    "type": "string"
                },
                "creditattempt": {
                    "type": "integer"
                },
                "grademode": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "registration.GetRegistrationHistoryResponse": {
            "type": "object",
            "properties": {
                "acadYear": {
                    "type": "integer"
                },
                "course": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.GetRegistrationHistoryCourseResponse"
                    }
                },
                "registrationDate": {
                    "type": "string"
                },
                "semester": {
                    "type": "integer"
                },
                "sequence": {
                    "type": "integer"
                },
                "studentId": {
                    "type": "string"
                }
            }
        },
        "registration.GetRegistrationStatusResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/registration.InfoRegister"
                },
                "status": {
                    "$ref": "#/definitions/registration.StatusEnum"
                }
            }
        },
        "registration.InfoRegister": {
            "type": "object",
            "properties": {
                "responseREG": {
                    "$ref": "#/definitions/registration.ConfirmResponse"
                },
                "statusCode": {
                    "type": "string"
                }
            }
        },
        "registration.Instructors": {
            "type": "object",
            "properties": {
                "extendPrefix": {
                    "type": "string"
                },
                "extendPrefixEng": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "firstNameEng": {
                    "type": "string"
                },
                "instructorId": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "lastNameEng": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "prefixEng": {
                    "type": "string"
                }
            }
        },
        "registration.NewsResponse": {
            "type": "object",
            "properties": {
                "announcerId": {
                    "type": "string"
                },
                "campus": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "categoryId": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createBy": {
                    "type": "string"
                },
                "createDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imageBanner": {
                    "type": "string"
                },
                "imageBannerName": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "newsId": {
                    "type": "string"
                },
                "publishDate": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "unpublishDate": {
                    "type": "string"
                },
                "updateBy": {
                    "type": "string"
                },
                "updateDate": {
                    "type": "string"
                }
            }
        },
        "registration.Program": {
            "type": "object",
            "properties": {
                "departmentId": {
                    "type": "integer"
                },
                "departmentName": {
                    "type": "string"
                },
                "departmentNameEng": {
                    "type": "string"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "facultyNameEng": {
                    "type": "string"
                }
            }
        },
        "registration.RegistrationPeriodResponse": {
            "type": "object",
            "properties": {
                "addDeleteExchangeEndDate": {
                    "type": "string"
                },
                "addDeleteExchangeStartDate": {
                    "type": "string"
                },
                "confirmEndDate": {
                    "type": "string"
                },
                "confirmStartDate": {
                    "type": "string"
                },
                "isAddDeleteExchangePeriod": {
                    "type": "boolean"
                },
                "isConfirmationRegistrationPeriod": {
                    "type": "boolean"
                },
                "isPaymentPeriod": {
                    "type": "boolean"
                },
                "paymentEndDate": {
                    "type": "string"
                },
                "paymentStartDate": {
                    "type": "string"
                }
            }
        },
        "registration.ReserveInfo": {
            "type": "object",
            "properties": {
                "campusId": {
                    "type": "integer"
                },
                "campusName": {
                    "type": "string"
                },
                "campusNameEng": {
                    "type": "string"
                },
                "departmentId": {
                    "type": "integer"
                },
                "departmentName": {
                    "type": "string"
                },
                "departmentNameEng": {
                    "type": "string"
                },
                "facultyId": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                },
                "facultyNameEng": {
                    "type": "string"
                },
                "reserveInfo": {
                    "type": "string"
                },
                "seatInfo": {
                    "$ref": "#/definitions/registration.SeatQuantity"
                }
            }
        },
        "registration.SeatQuantity": {
            "type": "object",
            "properties": {
                "reserved": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "registration.SectionInfo": {
            "type": "object",
            "properties": {
                "classId": {
                    "type": "integer"
                },
                "instructors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.Instructors"
                    }
                },
                "isInProgramStructure": {
                    "type": "boolean"
                },
                "isReserveSeat": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.SectionSchedules"
                    }
                },
                "seatInfo": {
                    "$ref": "#/definitions/registration.SeatQuantity"
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "registration.SectionSchedules": {
            "type": "object",
            "properties": {
                "endTime": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "weekDay": {
                    "type": "integer"
                },
                "weekDayName": {
                    "type": "string"
                }
            }
        },
        "registration.SectionTracking": {
            "type": "object",
            "properties": {
                "classId": {
                    "type": "integer"
                },
                "instructors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.Instructors"
                    }
                },
                "isInProgramStructure": {
                    "type": "boolean"
                },
                "isReserveSeat": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.SectionSchedules"
                    }
                },
                "seatInfo": {
                    "$ref": "#/definitions/registration.SeatQuantity"
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "registration.StatusEnum": {
            "type": "string",
            "enum": [
                "SUCCESS",
                "FAILED",
                "RETRY",
                "PROCESS"
            ],
            "x-enum-varnames": [
                "SubmissionStatusSuccess",
                "SubmissionStatusFailed",
                "SubmissionStatusRetry",
                "SubmissionStatusProcess"
            ]
        },
        "registration.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "registration.Tracking": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/registration.CourseTracking"
                    }
                },
                "errorString": {
                    "type": "string"
                },
                "errorid": {
                    "type": "integer"
                },
                "registrationStatus": {},
                "sequenceConfirm": {
                    "type": "integer"
                },
                "sequenceSubmit": {
                    "type": "integer"
                }
            }
        },
        "version.Response": {
            "type": "object",
            "properties": {
                "build": {
                    "type": "string"
                },
                "buildTime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Registration API",
	Description:      "This file for generate swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
